name: founderx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  animated_text_kit: ^4.2.3
  connectivity_plus: ^6.1.5
  dartz: ^0.10.1
  device_preview: ^1.3.1
  dio: ^5.9.0
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_otp_text_field: ^1.5.1+1
  flutter_svg: ^2.2.0
  flutter_web_auth_2: ^4.1.0
  get_it: ^8.2.0
  google_fonts: ^6.3.0
  internet_connection_checker: ^3.0.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/splash_feature/
   - assets/boarding_feature/
   - assets/localization/
   - assets/auth_feature/gif/
   - assets/auth_feature/images/
   - assets/auth_feature/icons/
   - assets/dashboard_feature/
   - assets/setUp_profile_feature/
   - assets/core/
   - assets/download_pdf/
   - assets/re_enterPitch/icons/
   - assets/re_enterPitch/images/
   - assets/test_images/
   - assets/investors_features/