name: founderx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.0
  get_it: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/splash_feature/