name: Flutter CI/CD

on:
  push:
    branches:
      - main
     
  pull_request:
    branches:
      - main

permissions:
  contents: write  # 👈 عشان يقدر يعمل push للتاجات

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Code 
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter Version 3.35.1
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create Tag
        run: |
          VERSION="v1.0.${{ github.run_number }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $VERSION
          git push origin $VERSION

      - name: Upload Release APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
